[[redirects]]
  from = "/posts/2019/02/01/architecture-decision-record.html"
  to = "/posts/2020/01/02/architecture-decision-record.html"
  status = 301

[[redirects]]
  from = "https://learn.me2resh.com"
  to = "https://www.youtube.com/channel/UCSWXhtIxc1HyMOGgW7RqzEA"
  status = 200
  force = true